
(defpackage "COM.INFORMATIMAGO.COMMAND.SCRIPT"
  (:nicknames "SCRIPT")
  (:use "COMMON-LISP"
        "COM.INFORMATIMAGO.COMMON-LISP.CESARUM.STRING"
        "COM.INFORMATIMAGO.COMMON-LISP.CESARUM.UTILITY"
        "COM.INFORMATIMAGO.COMMON-LISP.CESARUM.VERSION")
  (:export
   "*VERBOSE*" "*DEBUG*"
   "*DEFAULT-PROGRAM-NAME*" "*PROGRAM-NAME*" "*PROGRAM-PATH*" "*ARGUMENTS*"
   "PROGRAM-NAME" "ARGUMENTS"

   "WITHOUT-OUTPUT" "WITH-PAGER"
   "REDIRECTING-STDOUT-TO-STDERR"
   "RELAUNCH-WITH-KFULL-LINKSET-IF-NEEDED"

                                        ; I/O
   "PERROR" "PMESSAGE" "PQUERY")

  (:export                              ; Exit codes:
   "EX--BASE" "EX--MAX" "EX-CANTCREAT" "EX-CONFIG"
   "EX-DATAERR" "EX-IOERR" "EX-NOHOST" "EX-NOINPUT"
   "EX-NOPERM" "EX-NOUSER" "EX-OK" "EX-OSERR" "EX-OSFILE"
   "EX-PROTOCOL" "EX-SOFTWARE" "EX-TEMPFAIL" "EX-UNAVAILABLE"
   "EX-USAGE"
   "EXIT")

  (:export                              ; Commands
   "*COMMAND*"
   "COMMAND" "COMMANDP" "COPY-COMMAND" "COMMAND-OPTIONS"
   "COMMAND-DOCUMENTATION" "COMMAND-BASH-COMPLETION-HOOK"
   "REGISTER-COMMAND" "COMMAND-NAMED"
   "COMMAND-NAME" "COMMAND-USE-SYSTEMS" "COMMAND-MAIN" "COMMAND-PACKAGE"
   "COMMAND-PATHNAME"
   "COMMAND-PACKAGE-NAME"
   "REGISTER-COMMAND-FILE"
   "DISPATCH-COMMAND")

  (:export                              ; Options
   "OPTION" "OPTIONP" "COPY-OPTION" "OPTION-KEYS" "OPTION-ARGUMENTS"
   "OPTION-DOCUMENTATION" "OPTION-FUNCTION"
   "CALL-OPTION-FUNCTION" "PARSE-OPTIONS"
   "HELP-OPTION" "BASH-COMPLETION-OPTIONS")

  (:export                              ; Utilities:
   "FIND-DIRECTORIES"
   "CONCAT"
   "GETENV" "GETPID" "GETUID"
   "SHELL-QUOTE-ARGUMENT" "SHELL" "EXECUTE" "RUN-PROGRAM"
   "UNAME" "CP"  "MAKE-SYMBOLIC-LINK" "MAKE-DIRECTORY"))



(defpackage "COM.INFORMATIMAGO.COMMAND"
  (:use "COMMON-LISP"
        "COM.INFORMATIMAGO.COMMAND.SCRIPT")
  (:export "*ALL-COMMANDS*"))



(defpackage "COM.INFORMATIMAGO.COMMAND.GENERATE"
  (:use "COMMON-LISP"
        "COM.INFORMATIMAGO.COMMAND.SCRIPT"
        "COM.INFORMATIMAGO.COMMAND"))


